name: Autolabeler
on:
  issues:
    types: [opened, edited]
jobs:
  autolabeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/1-report-issue.yml
      - run: echo "ISSUE_LABELS=$(echo '${{ fromJSON(steps.issue-parser.outputs.jsonString).services }}' | tr '[:upper:]' '[:lower:]' | sed 's/"//g' | sed 's/ //g')" >> $GITHUB_ENV
      - uses: andymckay/labeler@master
        with:
          add-labels: "${{ env.ISSUE_LABELS }}, triage"
          remove-labels: "other"
      - name: Show Information
        run: |
          echo "This workflow run is triggered by ${{ github.event_name }} ."
          echo " *****************************************************************************"
          echo "$GITHUB_CONTEXT"
          echo " *****************************************************************************"
